//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HL7BrokerSuite.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class DataAccess : global::System.Configuration.ApplicationSettingsBase {
        
        private static DataAccess defaultInstance = ((DataAccess)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DataAccess())));
        
        public static DataAccess Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=[SERVER];Initial Catalog=[DATABASE];User Id=[USERNAME];Password=[PASS" +
            "WORD]")]
        public string BASE_CONNECTION_STRING {
            get {
                return ((string)(this["BASE_CONNECTION_STRING"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbo.Shields_HL7Broker_InsertIntoUpdateSysApplication")]
        public string PUT_APPLICATION {
            get {
                return ((string)(this["PUT_APPLICATION"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbo.Shields_HL7Broker_InsertIntoUpdateSysColumnSet")]
        public string PUT_COLUMN_SET {
            get {
                return ((string)(this["PUT_COLUMN_SET"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbo.Shields_HL7Broker_InsertIntoUpdateSysCredential")]
        public string PUT_CREDENTIAL {
            get {
                return ((string)(this["PUT_CREDENTIAL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbo.Shields_HL7Broker_InsertIntoUpdateSysCredentialType")]
        public string PUT_CREDENTIAL_TYPE {
            get {
                return ((string)(this["PUT_CREDENTIAL_TYPE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbo.Shields_HL7Broker_InsertIntoUpdateSysDatabaseInstance")]
        public string PUT_DATABASE_INSTANCE {
            get {
                return ((string)(this["PUT_DATABASE_INSTANCE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbo.Shields_HL7Broker_InsertIntoUpdateSysDatabaseTable")]
        public string PUT_DATABASE_TABLE {
            get {
                return ((string)(this["PUT_DATABASE_TABLE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbo.Shields_HL7Broker_InsertIntoUpdateSysInterface")]
        public string PUT_INTERFACE {
            get {
                return ((string)(this["PUT_INTERFACE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbo.Shields_HL7Broker_InsertIntoUpdateSysMessageGroup")]
        public string PUT_MESSAGE_GROUP {
            get {
                return ((string)(this["PUT_MESSAGE_GROUP"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbo.Shields_HL7Broker_InsertIntoUpdateSysMessageGroupInstance")]
        public string PUT_MESSAGE_GROUP_INSTANCE {
            get {
                return ((string)(this["PUT_MESSAGE_GROUP_INSTANCE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbo.Shields_HL7Broker_InsertIntoUpdateSysMessagePart")]
        public string PUT_MESSAGE_PART {
            get {
                return ((string)(this["PUT_MESSAGE_PART"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbo.Shields_HL7Broker_InsertIntoUpdateSysMessageType")]
        public string PUT_MESSAGE_TYPE {
            get {
                return ((string)(this["PUT_MESSAGE_TYPE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbo.Shields_HL7Broker_InsertIntoUpdateSysSegmentType")]
        public string PUT_SEGMENT_TYPE {
            get {
                return ((string)(this["PUT_SEGMENT_TYPE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM vShieldsHL7Broker_GetApplicationDatabasesConfig")]
        public string GET_APPLICATION_DATABASE_CONFIG {
            get {
                return ((string)(this["GET_APPLICATION_DATABASE_CONFIG"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM vShieldsHL7Broker_GetApplicationInterfaceConfig")]
        public string GET_APPLICATION_INTERFACE_CONFIG {
            get {
                return ((string)(this["GET_APPLICATION_INTERFACE_CONFIG"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_APPLICATION]")]
        public string GET_ALL_APPLICATION {
            get {
                return ((string)(this["GET_ALL_APPLICATION"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_COLUMN_SET]")]
        public string GET_ALL_COLUMN_SET {
            get {
                return ((string)(this["GET_ALL_COLUMN_SET"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_CREDENTIAL]")]
        public string GET_ALL_CREDENTIAL {
            get {
                return ((string)(this["GET_ALL_CREDENTIAL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_CREDENTIAL_TYPE]")]
        public string GET_ALL_CREDENTIAL_TYPE {
            get {
                return ((string)(this["GET_ALL_CREDENTIAL_TYPE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_DATABASE_INSTANCE]")]
        public string GET_ALL_DATABASE_INSTANCE {
            get {
                return ((string)(this["GET_ALL_DATABASE_INSTANCE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_DATABASE_TABLE]")]
        public string GET_ALL_DATABASE_TABLE {
            get {
                return ((string)(this["GET_ALL_DATABASE_TABLE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_INTERFACE]")]
        public string GET_ALL_INTERFACE {
            get {
                return ((string)(this["GET_ALL_INTERFACE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_MESSAGE_GROUP]")]
        public string GET_ALL_MESSAGE_GROUP {
            get {
                return ((string)(this["GET_ALL_MESSAGE_GROUP"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_MESSAGE_GROUP_INSTANCE]")]
        public string GET_ALL_MESSAGE_GROUP_INSTANCE {
            get {
                return ((string)(this["GET_ALL_MESSAGE_GROUP_INSTANCE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_MESSAGE_PART]")]
        public string GET_ALL_MESSAGE_PART {
            get {
                return ((string)(this["GET_ALL_MESSAGE_PART"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_MESSAGE_TYPE]")]
        public string GET_ALL_MESSAGE_TYPE {
            get {
                return ((string)(this["GET_ALL_MESSAGE_TYPE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_SEGMENT_TYPE]")]
        public string GET_ALL_SEGMENT_TYPE {
            get {
                return ((string)(this["GET_ALL_SEGMENT_TYPE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DELETE FROM [dbo].[SYS_APPLICATION] WHERE [ID] = @ID")]
        public string DELETE_APPLICATION {
            get {
                return ((string)(this["DELETE_APPLICATION"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_APPLICATION] WHERE [ID] = @ID")]
        public string GET_SINGLE_APPLICATION {
            get {
                return ((string)(this["GET_SINGLE_APPLICATION"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DELETE FROM [dbo].[SYS_COLUMN_SET] WHERE [ID] = @ID")]
        public string DELETE_COLUMN_SET {
            get {
                return ((string)(this["DELETE_COLUMN_SET"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM  [dbo].[SYS_COLUMN_SET] WHERE [ID] = @ID")]
        public string GET_SINGLE_COLUMN_SET {
            get {
                return ((string)(this["GET_SINGLE_COLUMN_SET"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbo.Shields_HL7Broker_InsertIntoUpdateSysDirectionType")]
        public string PUT_DIRECTION_TYPE {
            get {
                return ((string)(this["PUT_DIRECTION_TYPE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbo.Shields_HL7Broker_InsertIntoUpdateSysCommunicationType")]
        public string PUT_COMMUNICATION_TYPE {
            get {
                return ((string)(this["PUT_COMMUNICATION_TYPE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbo.Shields_HL7Broker_InsertIntoUpdateSysCommunication")]
        public string PUT_COMMUNICATION {
            get {
                return ((string)(this["PUT_COMMUNICATION"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_COMMUNICATION]")]
        public string GET_ALL_COMMUNICATION {
            get {
                return ((string)(this["GET_ALL_COMMUNICATION"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_COMMUNICATION_TYPE]")]
        public string GET_ALL_COMMUNICATION_TYPE {
            get {
                return ((string)(this["GET_ALL_COMMUNICATION_TYPE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_DIRECTION_TYPE]")]
        public string GET_ALL_DIRECTION_TYPE {
            get {
                return ((string)(this["GET_ALL_DIRECTION_TYPE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_COMMUNICATION] WHERE [ID] = @ID")]
        public string GET_SINGLE_COMMUNICATION {
            get {
                return ((string)(this["GET_SINGLE_COMMUNICATION"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DELETE FROM [dbo].[SYS_COMMUNICATION] WHERE [ID] = @ID")]
        public string DELETE_COMMUNICATION {
            get {
                return ((string)(this["DELETE_COMMUNICATION"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_COMMUNICATION_TYPE] WHERE [ID] = @ID")]
        public string GET_SINGLE_COMMUNICATION_TYPE {
            get {
                return ((string)(this["GET_SINGLE_COMMUNICATION_TYPE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_CREDENTIAL] WHERE [ID] = @ID")]
        public string GET_SINGLE_CREDENTIAL {
            get {
                return ((string)(this["GET_SINGLE_CREDENTIAL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_CREDENTIAL_TYPE] WHERE [ID] = @ID")]
        public string GET_SINGLE_CREDENTIAL_TYPE {
            get {
                return ((string)(this["GET_SINGLE_CREDENTIAL_TYPE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_DATABASE_INSTANCE] WHERE [ID] = @ID")]
        public string GET_SINGLE_DATABASE_INSTANCE {
            get {
                return ((string)(this["GET_SINGLE_DATABASE_INSTANCE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_DATABASE_TABLE] WHERE [ID] = @ID")]
        public string GET_SINGLE_DATABASE_TABLE {
            get {
                return ((string)(this["GET_SINGLE_DATABASE_TABLE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_DIRECTION_TYPE] WHERE [ID] = @ID")]
        public string GET_SINGLE_DIRECTION_TYPE {
            get {
                return ((string)(this["GET_SINGLE_DIRECTION_TYPE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_INTERFACE] WHERE [ID] = @ID")]
        public string GET_SINGLE_INTERFACE {
            get {
                return ((string)(this["GET_SINGLE_INTERFACE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_MESSAGE_GROUP] WHERE [ID] = @ID")]
        public string GET_SINGLE_MESSAGE_GROUP {
            get {
                return ((string)(this["GET_SINGLE_MESSAGE_GROUP"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_MESSAGE_GROUP_INSTANCE] WHERE [ID] = @ID")]
        public string GET_SINGLE_MESSAGE_GROUP_INSTANCE {
            get {
                return ((string)(this["GET_SINGLE_MESSAGE_GROUP_INSTANCE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_MESSAGE_PART] WHERE [ID] = @ID")]
        public string GET_SINGLE_MESSAGE_PART {
            get {
                return ((string)(this["GET_SINGLE_MESSAGE_PART"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_MESSAGE_TYPE]  WHERE [ID] = @ID")]
        public string GET_SINGLE_MESSAGE_TYPE {
            get {
                return ((string)(this["GET_SINGLE_MESSAGE_TYPE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_SEGMENT_TYPE] WHERE [ID] = @ID")]
        public string GET_SINGLE_SEGMENT_TYPE {
            get {
                return ((string)(this["GET_SINGLE_SEGMENT_TYPE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DELETE FROM [dbo].[SYS_COMMUNICATION_TYPE] WHERE [ID] = @ID")]
        public string DELETE_COMMUNICATION_TYPE {
            get {
                return ((string)(this["DELETE_COMMUNICATION_TYPE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DELETE FROM [dbo].[SYS_CREDENTIAL] WHERE [ID] = @ID")]
        public string DELETE_CREDENTIAL {
            get {
                return ((string)(this["DELETE_CREDENTIAL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DELETE FROM [dbo].[SYS_CREDENTIAL_TYPE] WHERE [ID] = @ID")]
        public string DELETE_CREDENTIAL_TYPE {
            get {
                return ((string)(this["DELETE_CREDENTIAL_TYPE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DELETE FROM [dbo].[SYS_DATABASE_INSTANCE] WHERE [ID] = @ID")]
        public string DELETE_DATABASE_INSTANCE {
            get {
                return ((string)(this["DELETE_DATABASE_INSTANCE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DELETE FROM [dbo].[SYS_DATABASE_TABLE] WHERE [ID] = @ID")]
        public string DELETE_DATABASE_TABLE {
            get {
                return ((string)(this["DELETE_DATABASE_TABLE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DELETE FROM [dbo].[SYS_DIRECTION_TYPE] WHERE [ID] = @ID")]
        public string DELETE_DIRECTION_TYPE {
            get {
                return ((string)(this["DELETE_DIRECTION_TYPE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DELETE FROM [dbo].[SYS_INTERFACE] WHERE [ID] = @ID")]
        public string DELETE_INTERFACE {
            get {
                return ((string)(this["DELETE_INTERFACE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DELETE FROM [dbo].[SYS_MESSAGE_GROUP] WHERE [ID] = @ID")]
        public string DELETE_MESSAGE_GROUP {
            get {
                return ((string)(this["DELETE_MESSAGE_GROUP"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DELETE FROM [dbo].[SYS_MESSAGE_GROUP_INSTANCE] WHERE [ID] = @ID")]
        public string DELETE_MESSAGE_GROUP_INSTANCE {
            get {
                return ((string)(this["DELETE_MESSAGE_GROUP_INSTANCE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DELETE FROM [dbo].[SYS_MESSAGE_PART] WHERE [ID] = @ID")]
        public string DELETE_MESSAGE_PART {
            get {
                return ((string)(this["DELETE_MESSAGE_PART"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DELETE FROM [dbo].[SYS_MESSAGE_TYPE] WHERE [ID] = @ID")]
        public string DELETE_MESSAGE_TYPE {
            get {
                return ((string)(this["DELETE_MESSAGE_TYPE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DELETE FROM [dbo].[SYS_SEGMENT_TYPE] WHERE [ID] = @ID")]
        public string DELETE_SEGMENT_TYPE {
            get {
                return ((string)(this["DELETE_SEGMENT_TYPE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[vShieldsHL7Broker_GetApplicationConfiguration] WHERE CONFIG_" +
            "ID = @CONFIG_ID")]
        public string SERVICE_VIEW_GET_APPLICATION_CONFIG {
            get {
                return ((string)(this["SERVICE_VIEW_GET_APPLICATION_CONFIG"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[vShieldsHL7Broker_GetApplicationDatabasesConfig] WHERE COMMU" +
            "NICATION_ID = @COMMUNICATION_ID ")]
        public string SERVICE_VIEW_GET_APPLICATION_DATABASE_CONFIG {
            get {
                return ((string)(this["SERVICE_VIEW_GET_APPLICATION_DATABASE_CONFIG"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[vShieldsHL7Broker_GetApplicationInterfaceConfig] WHERE COMMU" +
            "NICATION_ID = @COMMUNICATION_ID ")]
        public string SERVICE_VIEW_GET_APPLICATION_INTERFACE_CONFIG {
            get {
                return ((string)(this["SERVICE_VIEW_GET_APPLICATION_INTERFACE_CONFIG"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT  *  FROM [dbo].[vShieldsHL7Broker_GetDatabaseTables] WHERE DATABASE_INSTAN" +
            "CE_ID = @DATABASE_INSTANCE_ID")]
        public string SERVICE_VIEW_GET_DATABASE_TABLES {
            get {
                return ((string)(this["SERVICE_VIEW_GET_DATABASE_TABLES"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[vShieldsHL7Broker_GetDatabaseColumns] WHERE DATABASE_TABLE_I" +
            "D = @DATABASE_TABLE_ID")]
        public string SERVICE_VIEW_GET_DATABASE_COLUMNS {
            get {
                return ((string)(this["SERVICE_VIEW_GET_DATABASE_COLUMNS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[vShieldsHL7Broker_GetMessagePosition] WHERE MESSAGE_GROUP_IN" +
            "STANCE_ID = @MESSAGE_GROUP_INSTANCE_ID")]
        public string SERVICE_VIEW_GET_MESSAGE_POSITION {
            get {
                return ((string)(this["SERVICE_VIEW_GET_MESSAGE_POSITION"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[vShieldsHL7Broker_GetApplicationConfiguration]")]
        public string SERVICE_VIEW_GET_ALL_APPLICATION_CONFIG {
            get {
                return ((string)(this["SERVICE_VIEW_GET_ALL_APPLICATION_CONFIG"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("INSERT INTO #TABLE#  (#COLUMNS#) VALUES (#COLUMN_VALUES#);")]
        public string SERVICE_BASE_QUERY_INSERT {
            get {
                return ((string)(this["SERVICE_BASE_QUERY_INSERT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_DATABASE_TABLE_RELATION]")]
        public string GET_ALL_DATABASE_TABLE_RELATION {
            get {
                return ((string)(this["GET_ALL_DATABASE_TABLE_RELATION"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[dbo].[Shields_HL7Broker_InsertIntoUpdateSysDatabaseTableRelation]")]
        public string PUT_DATABASE_TABLE_RELATION {
            get {
                return ((string)(this["PUT_DATABASE_TABLE_RELATION"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DELETE FROM [dbo].[SYS_DATABASE_TABLE_RELATION] WHERE [ID] = @ID")]
        public string DELETE_DATABASE_TABLE_RELATION {
            get {
                return ((string)(this["DELETE_DATABASE_TABLE_RELATION"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_DATABASE_TABLE_RELATION] WHERE [ID] = @ID")]
        public string GET_SINGLE_DATABASE_TABLE_RELATION {
            get {
                return ((string)(this["GET_SINGLE_DATABASE_TABLE_RELATION"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_DATABASE_TABLE_RELATION] WHERE SOURCE_DATABASE_TABLE_ID " +
            "= @ID")]
        public string GET_SINGLE_DATABASE_TABLE_RELATION_BY_SOURCE {
            get {
                return ((string)(this["GET_SINGLE_DATABASE_TABLE_RELATION_BY_SOURCE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[dbo].[Shields_HL7Broker_InsertIntoAppMessageLog]")]
        public string POST_MESSAGE_LOG_PROCEDURE {
            get {
                return ((string)(this["POST_MESSAGE_LOG_PROCEDURE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[dbo].[Shields_HL7Broker_InsertIntoAppAcknowledgement]")]
        public string POST_ACKNOWLEDGEMENT_PROCEDURE {
            get {
                return ((string)(this["POST_ACKNOWLEDGEMENT_PROCEDURE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[dbo].[Shields_HL7Broker_InsertIntoUpdateSysWebServiceInstance]")]
        public string PUT_WEBSERVICE_INSTANCE {
            get {
                return ((string)(this["PUT_WEBSERVICE_INSTANCE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[dbo].[Shields_HL7Broker_InsertIntoUpdateSysWebserviceObject]")]
        public string PUT_WEBSERVICE_OBJECT {
            get {
                return ((string)(this["PUT_WEBSERVICE_OBJECT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[dbo].[Shields_HL7Broker_InsertIntoUpdateSysWebserviceProperty]")]
        public string PUT_WEBSERVICE_PROPERTY {
            get {
                return ((string)(this["PUT_WEBSERVICE_PROPERTY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_WEBSERVICE_INSTANCE]\t WHERE [ID] = @ID")]
        public string GET_SINGLE_WEBSERVICE_INSTANCE {
            get {
                return ((string)(this["GET_SINGLE_WEBSERVICE_INSTANCE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_WEBSERVICE_OBJECT] WHERE [ID] = @ID")]
        public string GET_SINGLE_WEBSERVICE_OBJECT {
            get {
                return ((string)(this["GET_SINGLE_WEBSERVICE_OBJECT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_WEBSERVICE_PROPERTY_SET] \tWHERE [ID] = @ID")]
        public string GET_SINGLE_WEBSERVICE_PROPERTY_SET {
            get {
                return ((string)(this["GET_SINGLE_WEBSERVICE_PROPERTY_SET"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DELETE FROM [dbo].[SYS_WEBSERVICE_INSTANCE] WHERE [ID] = @ID")]
        public string DELETE_WEBSERVICE_INSTANCE {
            get {
                return ((string)(this["DELETE_WEBSERVICE_INSTANCE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DELETE FROM [dbo].[SYS_WEBSERVICE_OBJECT] WHERE [ID] = @ID")]
        public string DELETE_WEBSERVICE_OBJECT {
            get {
                return ((string)(this["DELETE_WEBSERVICE_OBJECT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DELETE FROM [dbo].[SYS_WEBSERVICE_PROPERTY_SET] WHERE [ID] = @ID")]
        public string DELETE_WEBSERVICE_PROPERTY_SET {
            get {
                return ((string)(this["DELETE_WEBSERVICE_PROPERTY_SET"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[vShieldsHL7Broker_GetApplicationWebserviceConfig] WHERE [COM" +
            "MUNICATION_ID] = @COMMUNICATION")]
        public string SERVICE_VIEW_GET_WEBSERVICE_CONFIG {
            get {
                return ((string)(this["SERVICE_VIEW_GET_WEBSERVICE_CONFIG"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[vShieldsHL7Broker_GetWebseviceObjects] WHERE WEBSERVICE_INST" +
            "ANCE_ID = @WEBSERVICE_INSTANCE_ID")]
        public string SERVICE_VIEW_GET_WEBSERVICE_OBJECTS {
            get {
                return ((string)(this["SERVICE_VIEW_GET_WEBSERVICE_OBJECTS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[vShieldsHL7Broker_GetWebserviceObjectProperties] WHERE [WEBS" +
            "ERVICE_OBJECT_ID] = @WEBSERVICE_OBJECT_ID")]
        public string SERVICE_VIEW_GET_WEBSERVICE_PROPERTIES {
            get {
                return ((string)(this["SERVICE_VIEW_GET_WEBSERVICE_PROPERTIES"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_WEBSERVICE_INSTANCE]")]
        public string GET_ALL_WEBSERVICE_INSTANCE {
            get {
                return ((string)(this["GET_ALL_WEBSERVICE_INSTANCE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_WEBSERVICE_OBJECT]")]
        public string GET_ALL_WEBSERVICE_OBJECT {
            get {
                return ((string)(this["GET_ALL_WEBSERVICE_OBJECT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_WEBSERVICE_PROPERTY_SET]")]
        public string GET_ALL_WEBSERVICE_PROPERTY_SET {
            get {
                return ((string)(this["GET_ALL_WEBSERVICE_PROPERTY_SET"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [DBO].[APP_MESSAGE_HEADER_INSTANCE]")]
        public string GET_ALL_MESSAGE_HEADER_INSTANCE {
            get {
                return ((string)(this["GET_ALL_MESSAGE_HEADER_INSTANCE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [DBO].[APP_MESSAGE]")]
        public string GET_ALL_MESSAGE {
            get {
                return ((string)(this["GET_ALL_MESSAGE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[APP_MESSAGE_HEADER_INSTANCE] WHERE [ID] = @ID")]
        public string GET_SINGLE_MESSAGE_HEADER_INSTANCE {
            get {
                return ((string)(this["GET_SINGLE_MESSAGE_HEADER_INSTANCE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[APP_MESSAGE] WHERE [ID] = @ID")]
        public string GET_SINGLE_MESSAGE {
            get {
                return ((string)(this["GET_SINGLE_MESSAGE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DELETE FROM [dbo].[APP_MESSAGE_HEADER_INSTANCE] WHERE [ID] = @ID")]
        public string DELETE_MESSAGE_HEADER_INSTANCE {
            get {
                return ((string)(this["DELETE_MESSAGE_HEADER_INSTANCE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DELETE FROM [dbo].[APP_MESSAGE] WHERE [ID] = @ID")]
        public string DELETE_MESSAGE {
            get {
                return ((string)(this["DELETE_MESSAGE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT top 1 * FROM [dbo].[vShieldsHL7Broker_GetMessageHeaderInstances] WHERE [MH" +
            "I_SENDING_APPLICATION] = @MHI_SENDING_APPLICATION AND MHI_PROCESSED = @MHI_PROCE" +
            "SSED ORDER BY MHI_CREATED_DTTM, MHI_PENDING_REPROCESS_DTTM")]
        public string SERVICE_VIEW_GET_MESSAGE_HEADER_INSTANCES {
            get {
                return ((string)(this["SERVICE_VIEW_GET_MESSAGE_HEADER_INSTANCES"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[dbo].[Shields_HL7Broker_UpdateAppMessageHeaderInstanceToProcessed]")]
        public string UPDATE_MESSAGE_HEADER_INSTANCE_PROCESS {
            get {
                return ((string)(this["UPDATE_MESSAGE_HEADER_INSTANCE_PROCESS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[dbo].[Shields_HL7Broker_UpdateAppMessageHeaderInstanceForReProcess]")]
        public string UPDATE_MESSAGE_HEADER_INSTANCE_FOR_REPROCESS {
            get {
                return ((string)(this["UPDATE_MESSAGE_HEADER_INSTANCE_FOR_REPROCESS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[dbo].[Shields_HL7Broker_ResendReportFromSectraRIS]")]
        public string EXTERNAL_REPROCESS_RIS_REPORT {
            get {
                return ((string)(this["EXTERNAL_REPROCESS_RIS_REPORT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [DBO].[SYS_APPLICATION_SETTING]")]
        public string GET_ALL_APPLICATION_SETTING {
            get {
                return ((string)(this["GET_ALL_APPLICATION_SETTING"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [DBO].[SYS_APPLICATION_SETTING] WHERE ID = @ID")]
        public string GET_SINGLE_APPLICATION_SETTING {
            get {
                return ((string)(this["GET_SINGLE_APPLICATION_SETTING"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[dbo].[Shields_HL7Broker_InsertIntoUpdateSysApplicationSetting]")]
        public string PUT_APPLICATION_SETTING {
            get {
                return ((string)(this["PUT_APPLICATION_SETTING"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DELETE FROM [SYS].[SYS_APPLICATION_SETTING] WHERE ID = @ID")]
        public string DELETE_APPLICATION_SETTING {
            get {
                return ((string)(this["DELETE_APPLICATION_SETTING"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [DBO].[APP_BROKER] WHERE [ID] = @ID")]
        public string GET_SINGLE_BROKER {
            get {
                return ((string)(this["GET_SINGLE_BROKER"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [DBO].[APP_BROKER] ")]
        public string GET_ALL_BROKER {
            get {
                return ((string)(this["GET_ALL_BROKER"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[dbo].[Shields_HL7Broker_InsertIntoUpdateAppBroker]")]
        public string PUT_BROKER {
            get {
                return ((string)(this["PUT_BROKER"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[vShieldsHL7Broker_GetAppBrokerMainList] ")]
        public string SERVICE_VIEW_GET_BROKER_WORKLIST {
            get {
                return ((string)(this["SERVICE_VIEW_GET_BROKER_WORKLIST"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DELETE FROM [DBO].[APP_BROKER] WHERE [ID] = @ID")]
        public string DELETE_BROKER {
            get {
                return ((string)(this["DELETE_BROKER"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[dbo].[Shields_HL7Broker_UpdateAppBrokerInterfaceStatus]")]
        public string UPDATE_INTERFACE_STATUS {
            get {
                return ((string)(this["UPDATE_INTERFACE_STATUS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[dbo].[Shields_HL7Broker_UpdateAppBrokerProcessIdentity]")]
        public string UPDATE_PROCESS_IDENTITY {
            get {
                return ((string)(this["UPDATE_PROCESS_IDENTITY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[dbo].[Shields_HL7Broker_UpdateAppBrokerLastMessageStats]")]
        public string UPDATE_MESSAGE_STATS {
            get {
                return ((string)(this["UPDATE_MESSAGE_STATS"]));
            }
        }
    }
}
