//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HL7BrokerSuite.Sys.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class DataAccess : global::System.Configuration.ApplicationSettingsBase {
        
        private static DataAccess defaultInstance = ((DataAccess)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DataAccess())));
        
        public static DataAccess Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=[SERVER];Initial Catalog=[DATABASE];User Id=[USERNAME];Password=[PASS" +
            "WORD]")]
        public string BASE_CONNECTION_STRING {
            get {
                return ((string)(this["BASE_CONNECTION_STRING"]));
            }
            set {
                this["BASE_CONNECTION_STRING"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbo.Shields_HL7Broker_InsertIntoUpdateSysApplication")]
        public string PUT_APPLICATION {
            get {
                return ((string)(this["PUT_APPLICATION"]));
            }
            set {
                this["PUT_APPLICATION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbo.Shields_HL7Broker_InsertIntoUpdateSysColumnSet")]
        public string PUT_COLUMN_SET {
            get {
                return ((string)(this["PUT_COLUMN_SET"]));
            }
            set {
                this["PUT_COLUMN_SET"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbo.Shields_HL7Broker_InsertIntoUpdateSysCredential")]
        public string PUT_CREDENTIAL {
            get {
                return ((string)(this["PUT_CREDENTIAL"]));
            }
            set {
                this["PUT_CREDENTIAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbo.Shields_HL7Broker_InsertIntoUpdateSysCredentialType")]
        public string PUT_CREDENTIAL_TYPE {
            get {
                return ((string)(this["PUT_CREDENTIAL_TYPE"]));
            }
            set {
                this["PUT_CREDENTIAL_TYPE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbo.Shields_HL7Broker_InsertIntoUpdateSysDatabaseInstance")]
        public string PUT_DATABASE_INSTANCE {
            get {
                return ((string)(this["PUT_DATABASE_INSTANCE"]));
            }
            set {
                this["PUT_DATABASE_INSTANCE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbo.Shields_HL7Broker_InsertIntoUpdateSysDatabaseTable")]
        public string PUT_DATABASE_TABLE {
            get {
                return ((string)(this["PUT_DATABASE_TABLE"]));
            }
            set {
                this["PUT_DATABASE_TABLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbo.Shields_HL7Broker_InsertIntoUpdateSysInterface")]
        public string PUT_INTERFACE {
            get {
                return ((string)(this["PUT_INTERFACE"]));
            }
            set {
                this["PUT_INTERFACE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbo.Shields_HL7Broker_InsertIntoUpdateSysMessageGroup")]
        public string PUT_MESSAGE_GROUP {
            get {
                return ((string)(this["PUT_MESSAGE_GROUP"]));
            }
            set {
                this["PUT_MESSAGE_GROUP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbo.Shields_HL7Broker_InsertIntoUpdateSysMessageGroupInstance")]
        public string PUT_MESSAGE_GROUP_INSTANCE {
            get {
                return ((string)(this["PUT_MESSAGE_GROUP_INSTANCE"]));
            }
            set {
                this["PUT_MESSAGE_GROUP_INSTANCE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbo.Shields_HL7Broker_InsertIntoUpdateSysMessagePart")]
        public string PUT_MESSAGE_PART {
            get {
                return ((string)(this["PUT_MESSAGE_PART"]));
            }
            set {
                this["PUT_MESSAGE_PART"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbo.Shields_HL7Broker_InsertIntoUpdateSysMessageType")]
        public string PUT_MESSAGE_TYPE {
            get {
                return ((string)(this["PUT_MESSAGE_TYPE"]));
            }
            set {
                this["PUT_MESSAGE_TYPE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbo.Shields_HL7Broker_InsertIntoUpdateSysSegmentType")]
        public string PUT_SEGMENT_TYPE {
            get {
                return ((string)(this["PUT_SEGMENT_TYPE"]));
            }
            set {
                this["PUT_SEGMENT_TYPE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM vShieldsHL7Broker_GetApplicationDatabasesConfig")]
        public string GET_APPLICATION_DATABASE_CONFIG {
            get {
                return ((string)(this["GET_APPLICATION_DATABASE_CONFIG"]));
            }
            set {
                this["GET_APPLICATION_DATABASE_CONFIG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM vShieldsHL7Broker_GetApplicationInterfaceConfig")]
        public string GET_APPLICATION_INTERFACE_CONFIG {
            get {
                return ((string)(this["GET_APPLICATION_INTERFACE_CONFIG"]));
            }
            set {
                this["GET_APPLICATION_INTERFACE_CONFIG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_APPLICATION]")]
        public string GET_ALL_APPLICATION {
            get {
                return ((string)(this["GET_ALL_APPLICATION"]));
            }
            set {
                this["GET_ALL_APPLICATION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_COLUMN_SET]")]
        public string GET_ALL_COLUMN_SET {
            get {
                return ((string)(this["GET_ALL_COLUMN_SET"]));
            }
            set {
                this["GET_ALL_COLUMN_SET"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_CREDENTIAL]")]
        public string GET_ALL_CREDENTIAL {
            get {
                return ((string)(this["GET_ALL_CREDENTIAL"]));
            }
            set {
                this["GET_ALL_CREDENTIAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_CREDENTIAL_TYPE]")]
        public string GET_ALL_CREDENTIAL_TYPE {
            get {
                return ((string)(this["GET_ALL_CREDENTIAL_TYPE"]));
            }
            set {
                this["GET_ALL_CREDENTIAL_TYPE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_DATABASE_INSTANCE]")]
        public string GET_ALL_DATABASE_INSTANCE {
            get {
                return ((string)(this["GET_ALL_DATABASE_INSTANCE"]));
            }
            set {
                this["GET_ALL_DATABASE_INSTANCE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_DATABASE_TABLE]")]
        public string GET_ALL_DATABASE_TABLE {
            get {
                return ((string)(this["GET_ALL_DATABASE_TABLE"]));
            }
            set {
                this["GET_ALL_DATABASE_TABLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_INTERFACE]")]
        public string GET_ALL_INTERFACE {
            get {
                return ((string)(this["GET_ALL_INTERFACE"]));
            }
            set {
                this["GET_ALL_INTERFACE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_MESSAGE_GROUP]")]
        public string GET_ALL_MESSAGE_GROUP {
            get {
                return ((string)(this["GET_ALL_MESSAGE_GROUP"]));
            }
            set {
                this["GET_ALL_MESSAGE_GROUP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_MESSAGE_GROUP_INSTANCE]")]
        public string GET_ALL_MESSAGE_GROUP_INSTANCE {
            get {
                return ((string)(this["GET_ALL_MESSAGE_GROUP_INSTANCE"]));
            }
            set {
                this["GET_ALL_MESSAGE_GROUP_INSTANCE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_MESSAGE_PART]")]
        public string GET_ALL_MESSAGE_PART {
            get {
                return ((string)(this["GET_ALL_MESSAGE_PART"]));
            }
            set {
                this["GET_ALL_MESSAGE_PART"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_MESSAGE_TYPE]")]
        public string GET_ALL_MESSAGE_TYPE {
            get {
                return ((string)(this["GET_ALL_MESSAGE_TYPE"]));
            }
            set {
                this["GET_ALL_MESSAGE_TYPE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_SEGMENT_TYPE]")]
        public string GET_ALL_SEGMENT_TYPE {
            get {
                return ((string)(this["GET_ALL_SEGMENT_TYPE"]));
            }
            set {
                this["GET_ALL_SEGMENT_TYPE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DELETE FROM [dbo].[SYS_APPLICATION] WHERE [ID] = @ID")]
        public string DELETE_APPLICATION {
            get {
                return ((string)(this["DELETE_APPLICATION"]));
            }
            set {
                this["DELETE_APPLICATION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_APPLICATION] WHERE [ID] = @ID")]
        public string GET_SINGLE_APPLICATION {
            get {
                return ((string)(this["GET_SINGLE_APPLICATION"]));
            }
            set {
                this["GET_SINGLE_APPLICATION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DELETE FROM [dbo].[SYS_COLUMN_SET] WHERE [ID] = @ID")]
        public string DELETE_COLUMN_SET {
            get {
                return ((string)(this["DELETE_COLUMN_SET"]));
            }
            set {
                this["DELETE_COLUMN_SET"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM  [dbo].[SYS_COLUMN_SET] WHERE [ID] = @ID")]
        public string GET_SINGLE_COLUMN_SET {
            get {
                return ((string)(this["GET_SINGLE_COLUMN_SET"]));
            }
            set {
                this["GET_SINGLE_COLUMN_SET"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbo.Shields_HL7Broker_InsertIntoUpdateSysDirectionType")]
        public string PUT_DIRECTION_TYPE {
            get {
                return ((string)(this["PUT_DIRECTION_TYPE"]));
            }
            set {
                this["PUT_DIRECTION_TYPE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbo.Shields_HL7Broker_InsertIntoUpdateSysCommunicationType")]
        public string PUT_COMMUNICATION_TYPE {
            get {
                return ((string)(this["PUT_COMMUNICATION_TYPE"]));
            }
            set {
                this["PUT_COMMUNICATION_TYPE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbo.Shields_HL7Broker_InsertIntoUpdateSysCommunication")]
        public string PUT_COMMUNICATION {
            get {
                return ((string)(this["PUT_COMMUNICATION"]));
            }
            set {
                this["PUT_COMMUNICATION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_COMMUNICATION]")]
        public string GET_ALL_COMMUNICATION {
            get {
                return ((string)(this["GET_ALL_COMMUNICATION"]));
            }
            set {
                this["GET_ALL_COMMUNICATION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_COMMUNICATION_TYPE]")]
        public string GET_ALL_COMMUNICATION_TYPE {
            get {
                return ((string)(this["GET_ALL_COMMUNICATION_TYPE"]));
            }
            set {
                this["GET_ALL_COMMUNICATION_TYPE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_DIRECTION_TYPE]")]
        public string GET_ALL_DIRECTION_TYPE {
            get {
                return ((string)(this["GET_ALL_DIRECTION_TYPE"]));
            }
            set {
                this["GET_ALL_DIRECTION_TYPE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_COMMUNICATION] WHERE [ID] = @ID")]
        public string GET_SINGLE_COMMUNICATION {
            get {
                return ((string)(this["GET_SINGLE_COMMUNICATION"]));
            }
            set {
                this["GET_SINGLE_COMMUNICATION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DELETE FROM [dbo].[SYS_COMMUNICATION] WHERE [ID] = @ID")]
        public string DELETE_COMMUNICATION {
            get {
                return ((string)(this["DELETE_COMMUNICATION"]));
            }
            set {
                this["DELETE_COMMUNICATION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_COMMUNICATION_TYPE] WHERE [ID] = @ID")]
        public string GET_SINGLE_COMMUNICATION_TYPE {
            get {
                return ((string)(this["GET_SINGLE_COMMUNICATION_TYPE"]));
            }
            set {
                this["GET_SINGLE_COMMUNICATION_TYPE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_CREDENTIAL] WHERE [ID] = @ID")]
        public string GET_SINGLE_CREDENTIAL {
            get {
                return ((string)(this["GET_SINGLE_CREDENTIAL"]));
            }
            set {
                this["GET_SINGLE_CREDENTIAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_CREDENTIAL_TYPE] WHERE [ID] = @ID")]
        public string GET_SINGLE_CREDENTIAL_TYPE {
            get {
                return ((string)(this["GET_SINGLE_CREDENTIAL_TYPE"]));
            }
            set {
                this["GET_SINGLE_CREDENTIAL_TYPE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_DATABASE_INSTANCE] WHERE [ID] = @ID")]
        public string GET_SINGLE_DATABASE_INSTANCE {
            get {
                return ((string)(this["GET_SINGLE_DATABASE_INSTANCE"]));
            }
            set {
                this["GET_SINGLE_DATABASE_INSTANCE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_DATABASE_TABLE] WHERE [ID] = @ID")]
        public string GET_SINGLE_DATABASE_TABLE {
            get {
                return ((string)(this["GET_SINGLE_DATABASE_TABLE"]));
            }
            set {
                this["GET_SINGLE_DATABASE_TABLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_DIRECTION_TYPE] WHERE [ID] = @ID")]
        public string GET_SINGLE_DIRECTION_TYPE {
            get {
                return ((string)(this["GET_SINGLE_DIRECTION_TYPE"]));
            }
            set {
                this["GET_SINGLE_DIRECTION_TYPE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_INTERFACE] WHERE [ID] = @ID")]
        public string GET_SINGLE_INTERFACE {
            get {
                return ((string)(this["GET_SINGLE_INTERFACE"]));
            }
            set {
                this["GET_SINGLE_INTERFACE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_MESSAGE_GROUP] WHERE [ID] = @ID")]
        public string GET_SINGLE_MESSAGE_GROUP {
            get {
                return ((string)(this["GET_SINGLE_MESSAGE_GROUP"]));
            }
            set {
                this["GET_SINGLE_MESSAGE_GROUP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_MESSAGE_GROUP_INSTANCE] WHERE [ID] = @ID")]
        public string GET_SINGLE_MESSAGE_GROUP_INSTANCE {
            get {
                return ((string)(this["GET_SINGLE_MESSAGE_GROUP_INSTANCE"]));
            }
            set {
                this["GET_SINGLE_MESSAGE_GROUP_INSTANCE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_MESSAGE_PART] WHERE [ID] = @ID")]
        public string GET_SINGLE_MESSAGE_PART {
            get {
                return ((string)(this["GET_SINGLE_MESSAGE_PART"]));
            }
            set {
                this["GET_SINGLE_MESSAGE_PART"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_MESSAGE_TYPE]  WHERE [ID] = @ID")]
        public string GET_SINGLE_MESSAGE_TYPE {
            get {
                return ((string)(this["GET_SINGLE_MESSAGE_TYPE"]));
            }
            set {
                this["GET_SINGLE_MESSAGE_TYPE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[SYS_SEGMENT_TYPE] WHERE [ID] = @ID")]
        public string GET_SINGLE_SEGMENT_TYPE {
            get {
                return ((string)(this["GET_SINGLE_SEGMENT_TYPE"]));
            }
            set {
                this["GET_SINGLE_SEGMENT_TYPE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DELETE FROM [dbo].[SYS_COMMUNICATION_TYPE] WHERE [ID] = @ID")]
        public string DELETE_COMMUNICATION_TYPE {
            get {
                return ((string)(this["DELETE_COMMUNICATION_TYPE"]));
            }
            set {
                this["DELETE_COMMUNICATION_TYPE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DELETE FROM [dbo].[SYS_CREDENTIAL] WHERE [ID] = @ID")]
        public string DELETE_CREDENTIAL {
            get {
                return ((string)(this["DELETE_CREDENTIAL"]));
            }
            set {
                this["DELETE_CREDENTIAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DELETE FROM [dbo].[SYS_CREDENTIAL_TYPE] WHERE [ID] = @ID")]
        public string DELETE_CREDENTIAL_TYPE {
            get {
                return ((string)(this["DELETE_CREDENTIAL_TYPE"]));
            }
            set {
                this["DELETE_CREDENTIAL_TYPE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DELETE FROM [dbo].[SYS_DATABASE_INSTANCE] WHERE [ID] = @ID")]
        public string DELETE_DATABASE_INSTANCE {
            get {
                return ((string)(this["DELETE_DATABASE_INSTANCE"]));
            }
            set {
                this["DELETE_DATABASE_INSTANCE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DELETE FROM [dbo].[SYS_DATABASE_TABLE] WHERE [ID] = @ID")]
        public string DELETE_DATABASE_TABLE {
            get {
                return ((string)(this["DELETE_DATABASE_TABLE"]));
            }
            set {
                this["DELETE_DATABASE_TABLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DELETE FROM [dbo].[SYS_DIRECTION_TYPE] WHERE [ID] = @ID")]
        public string DELETE_DIRECTION_TYPE {
            get {
                return ((string)(this["DELETE_DIRECTION_TYPE"]));
            }
            set {
                this["DELETE_DIRECTION_TYPE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DELETE FROM [dbo].[SYS_INTERFACE] WHERE [ID] = @ID")]
        public string DELETE_INTERFACE {
            get {
                return ((string)(this["DELETE_INTERFACE"]));
            }
            set {
                this["DELETE_INTERFACE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DELETE FROM [dbo].[SYS_MESSAGE_GROUP] WHERE [ID] = @ID")]
        public string DELETE_MESSAGE_GROUP {
            get {
                return ((string)(this["DELETE_MESSAGE_GROUP"]));
            }
            set {
                this["DELETE_MESSAGE_GROUP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DELETE FROM [dbo].[SYS_MESSAGE_GROUP_INSTANCE] WHERE [ID] = @ID")]
        public string DELETE_MESSAGE_GROUP_INSTANCE {
            get {
                return ((string)(this["DELETE_MESSAGE_GROUP_INSTANCE"]));
            }
            set {
                this["DELETE_MESSAGE_GROUP_INSTANCE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DELETE FROM [dbo].[SYS_MESSAGE_PART] WHERE [ID] = @ID")]
        public string DELETE_MESSAGE_PART {
            get {
                return ((string)(this["DELETE_MESSAGE_PART"]));
            }
            set {
                this["DELETE_MESSAGE_PART"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DELETE FROM [dbo].[SYS_MESSAGE_TYPE] WHERE [ID] = @ID")]
        public string DELETE_MESSAGE_TYPE {
            get {
                return ((string)(this["DELETE_MESSAGE_TYPE"]));
            }
            set {
                this["DELETE_MESSAGE_TYPE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DELETE FROM [dbo].[SYS_SEGMENT_TYPE] WHERE [ID] = @ID")]
        public string DELETE_SEGMENT_TYPE {
            get {
                return ((string)(this["DELETE_SEGMENT_TYPE"]));
            }
            set {
                this["DELETE_SEGMENT_TYPE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[vShieldsHL7Broker_GetApplicationConfiguration] WHERE CONFIG_" +
            "ID = @CONFIG_ID")]
        public string SERVICE_VIEW_GET_APPLICATION_CONFIG {
            get {
                return ((string)(this["SERVICE_VIEW_GET_APPLICATION_CONFIG"]));
            }
            set {
                this["SERVICE_VIEW_GET_APPLICATION_CONFIG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[vShieldsHL7Broker_GetApplicationDatabasesConfig] WHERE COMMU" +
            "NICATION_ID = @COMMUNICATION_ID ")]
        public string SERVICE_VIEW_GET_APPLICATION_DATABASE_CONFIG {
            get {
                return ((string)(this["SERVICE_VIEW_GET_APPLICATION_DATABASE_CONFIG"]));
            }
            set {
                this["SERVICE_VIEW_GET_APPLICATION_DATABASE_CONFIG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[vShieldsHL7Broker_GetApplicationInterfaceConfig] WHERE COMMU" +
            "NICATION_ID = @COMMUNICATION_ID ")]
        public string SERVICE_VIEW_GET_APPLICATION_INTERFACE_CONFIG {
            get {
                return ((string)(this["SERVICE_VIEW_GET_APPLICATION_INTERFACE_CONFIG"]));
            }
            set {
                this["SERVICE_VIEW_GET_APPLICATION_INTERFACE_CONFIG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT  *  FROM [dbo].[vShieldsHL7Broker_GetDatabaseTables] WHERE DATABASE_INSTAN" +
            "CE_ID = @DATABASE_INSTANCE_ID")]
        public string SERVICE_VIEW_GET_DATABASE_TABLES {
            get {
                return ((string)(this["SERVICE_VIEW_GET_DATABASE_TABLES"]));
            }
            set {
                this["SERVICE_VIEW_GET_DATABASE_TABLES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[vShieldsHL7Broker_GetDatabaseColumns] WHERE DATABASE_TABLE_I" +
            "D = @DATABASE_TABLE_ID")]
        public string SERVICE_VIEW_GET_DATABASE_COLUMNS {
            get {
                return ((string)(this["SERVICE_VIEW_GET_DATABASE_COLUMNS"]));
            }
            set {
                this["SERVICE_VIEW_GET_DATABASE_COLUMNS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[vShieldsHL7Broker_GetMessagePosition] WHERE MESSAGE_GROUP_IN" +
            "STANCE_ID = @MESSAGE_GROUP_INSTANCE_ID")]
        public string SERVICE_VIEW_GET_MESSAGE_POSITION {
            get {
                return ((string)(this["SERVICE_VIEW_GET_MESSAGE_POSITION"]));
            }
            set {
                this["SERVICE_VIEW_GET_MESSAGE_POSITION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [dbo].[vShieldsHL7Broker_GetApplicationConfiguration]")]
        public string SERVICE_VIEW_GET_ALL_APPLICATION_CONFIG {
            get {
                return ((string)(this["SERVICE_VIEW_GET_ALL_APPLICATION_CONFIG"]));
            }
            set {
                this["SERVICE_VIEW_GET_ALL_APPLICATION_CONFIG"] = value;
            }
        }
    }
}
