//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HL7Broker.Service___Obsolete.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class DataAccess : global::System.Configuration.ApplicationSettingsBase {
        
        private static DataAccess defaultInstance = ((DataAccess)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DataAccess())));
        
        public static DataAccess Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=[SERVER];Initial Catalog=[DATABASE];User Id=[USERNAME];Password=[PASS" +
            "WORD]")]
        public string BASE_CONNECTION_STRING {
            get {
                return ((string)(this["BASE_CONNECTION_STRING"]));
            }
            set {
                this["BASE_CONNECTION_STRING"] = value;
            }
        }
    }
}
