CREATE FULLTEXT INDEX ON [dbo].[APP_MESSAGE_HEADER_INSTANCE]
    ([MESSAGE_CONTROL_ID] LANGUAGE 1033, [PATIENT_IDENTIFIER] LANGUAGE 1033)
    KEY INDEX [PK_APP_MESSAGE_HEADER_INSTANCE]
    ON [SHIELDS_INTERFACE_BROKER]
    WITH CHANGE_TRACKING OFF;

