CREATE TABLE [dbo].[APP_MESSAGE] (
    [ID]                         BIGINT IDENTITY (1, 1) NOT NULL,
    [MESSAGE_HEADER_INSTANCE_ID] BIGINT NULL,
    [HL7_RAW]                    TEXT   NULL,
    CONSTRAINT [PK_APP_MESSAGE] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_APP_MESSAGE_APP_MESSAGE_HEADER_INSTANCE] FOREIGN KEY ([MESSAGE_HEADER_INSTANCE_ID]) REFERENCES [dbo].[APP_MESSAGE_HEADER_INSTANCE] ([ID])
);

