CREATE TABLE [dbo].[APP_BROKER] (
    [ID]                  INT      IDENTITY (1, 1) NOT NULL,
    [INTERFACE_STATUS_ID] INT      NOT NULL,
    [COMMUNICATION_ID]    INT      NOT NULL,
    [PROCESS_ID]          INT      CONSTRAINT [DF_APP_BROKER_PROCESS_ID] DEFAULT ((0)) NOT NULL,
    [LAST_MESSAGE_ID]     BIGINT   NOT NULL,
    [QUEUE_COUNT]         INT      CONSTRAINT [DF_APP_BROKER_QUEUE_COUNT] DEFAULT ((0)) NOT NULL,
    [LAST_MESSAGE_DTTM]   DATETIME NULL,
    CONSTRAINT [PK_APP_BROKER] PRIMARY KEY CLUSTERED ([ID] ASC)
);



