CREATE TABLE [dbo].[APP_MESSAGE_HEADER_INSTANCE] (
    [ID]                     BIGINT        IDENTITY (1, 1) NOT NULL,
    [SENDING_APPLICATION]    NVARCHAR (50) NULL,
    [RECEIVING_APPLICATION]  NVARCHAR (50) NULL,
    [SENDING_FACILITY]       NVARCHAR (50) NULL,
    [RECEIVING_FACILTIY]     NVARCHAR (50) NULL,
    [MESSAGE_DTTM]           NVARCHAR (50) NULL,
    [MESSAGE_CONTROL_ID]     NVARCHAR (50) NULL,
    [MESSAGE_TYPE]           NVARCHAR (50) NULL,
    [VERSION_ID]             NVARCHAR (50) NULL,
    [APPLICATION_ACK_TYPE]   NVARCHAR (50) NULL,
    [ACCEPT_ACK_TYPE]        NVARCHAR (50) NULL,
    [ORDER_CONTROL_CODE]     NVARCHAR (50) NULL,
    [PATIENT_IDENTIFIER]     NVARCHAR (50) NULL,
    [PROCESSED]              BIT           CONSTRAINT [DF_MESSAGE_HEADER_INSTANCE_PROCSSED] DEFAULT ((0)) NULL,
    [PROCESSED_DTTM]         DATETIME      NULL,
    [PROCESSED_COUNT]        INT           CONSTRAINT [DF_APP_MESSAGE_HEADER_INSTANCE_PROCESSED_COUNT] DEFAULT ((0)) NULL,
    [PENDING_REPROCESS_DTTM] DATETIME      NULL,
    [CREATED_DTTM]           DATETIME      NULL,
    CONSTRAINT [PK_APP_MESSAGE_HEADER_INSTANCE] PRIMARY KEY CLUSTERED ([ID] ASC)
);










GO
CREATE NONCLUSTERED INDEX [_dta_index_APP_MESSAGE_HEADER_INSTANCE_6_238623893__K14_K5_K18_1_2_3_4_6_7_8_9_10_11_12_13_15_16_17]
    ON [dbo].[APP_MESSAGE_HEADER_INSTANCE]([PROCESSED] ASC, [RECEIVING_FACILTIY] ASC, [CREATED_DTTM] ASC)
    INCLUDE([ID], [SENDING_APPLICATION], [RECEIVING_APPLICATION], [SENDING_FACILITY], [MESSAGE_DTTM], [MESSAGE_CONTROL_ID], [MESSAGE_TYPE], [VERSION_ID], [APPLICATION_ACK_TYPE], [ACCEPT_ACK_TYPE], [ORDER_CONTROL_CODE], [PATIENT_IDENTIFIER], [PROCESSED_DTTM], [PROCESSED_COUNT], [PENDING_REPROCESS_DTTM]);


GO
CREATE STATISTICS [_dta_stat_238623893_5_14_18]
    ON [dbo].[APP_MESSAGE_HEADER_INSTANCE]([RECEIVING_FACILTIY], [PROCESSED], [CREATED_DTTM]);


GO
CREATE STATISTICS [_dta_stat_238623893_18_5]
    ON [dbo].[APP_MESSAGE_HEADER_INSTANCE]([CREATED_DTTM], [RECEIVING_FACILTIY]);

