CREATE TABLE [dbo].[SYS_INTERFACE] (
    [ID]               BIGINT         IDENTITY (1, 1) NOT NULL,
    [COMMUNICATION_ID] BIGINT         NULL,
    [CREDENTIAL_ID]    BIGINT         NULL,
    [IP_ADDRESS]       NVARCHAR (255) NULL,
    [PORT]             NVARCHAR (255) NULL,
    [MAX_CONNECTIONS]  INT            NULL,
    CONSTRAINT [PK_SYS_INTERFACE] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SYS_INTERFACE_SYS_CREDENTIAL] FOREIGN KEY ([CREDENTIAL_ID]) REFERENCES [dbo].[SYS_CREDENTIAL] ([ID])
);

