CREATE TABLE [dbo].[SYS_CREDENTIAL] (
    [ID]                 BIGINT         IDENTITY (1, 1) NOT NULL,
    [CREDENTIAL_TYPE_ID] BIGINT         NULL,
    [USERNAME]           NVARCHAR (255) NULL,
    [PASSWORD]           NVARCHAR (255) NULL,
    CONSTRAINT [PK_SYS_CREDENTIAL] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SYS_CREDENTIAL_SYS_CREDENTIAL_TYPE] FOREIGN KEY ([CREDENTIAL_TYPE_ID]) REFERENCES [dbo].[SYS_CREDENTIAL_TYPE] ([ID])
);

