CREATE TABLE [dbo].[SYS_MESSAGE_GROUP] (
    [ID]                        BIGINT IDENTITY (1, 1) NOT NULL,
    [MESSAGE_GROUP_INSTANCE_ID] BIGINT NULL,
    [MESSAGE_PART_ID]           BIGINT NOT NULL,
    [POSITION]                  INT    NULL,
    CONSTRAINT [PK_SYS_MESSAGE_PART_VALUE] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SYS_MESSAGE_GROUP_SYS_MESSAGE_GROUP_INSTANCE] FOREIGN KEY ([MESSAGE_GROUP_INSTANCE_ID]) REFERENCES [dbo].[SYS_MESSAGE_GROUP_INSTANCE] ([ID]),
    CONSTRAINT [FK_SYS_MESSAGE_GROUP_SYS_MESSAGE_PART] FOREIGN KEY ([MESSAGE_PART_ID]) REFERENCES [dbo].[SYS_MESSAGE_PART] ([ID])
);

