CREATE TABLE [dbo].[SYS_COMMUNICATION_TYPE] (
    [ID]   BIGINT        IDENTITY (1, 1) NOT NULL,
    [NAME] NVARCHAR (50) NULL,
    CONSTRAINT [PK_SYS_COMMUNICATION_TYPE] PRIMARY KEY CLUSTERED ([ID] ASC)
);

