CREATE TABLE [dbo].[SYS_MESSAGE_PART] (
    [ID]        BIGINT         IDENTITY (1, 1) NOT NULL,
    [NAME]      NVARCHAR (255) NULL,
    [DELIMITER] CHAR (2)       NULL,
    CONSTRAINT [PK_SYS_MESSAGE_PART] PRIMARY KEY CLUSTERED ([ID] ASC)
);



