CREATE TABLE [dbo].[SYS_DATABASE_TABLE] (
    [ID]                   BIGINT        IDENTITY (1, 1) NOT NULL,
    [DATABASE_INSTANCE_ID] BIGINT        NULL,
    [NAME]                 VARCHAR (100) NULL,
    CONSTRAINT [PK_SYS_DATABASE_TABLE] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SYS_DATABASE_TABLE_SYS_DATABASE_INSTANCE] FOREIGN KEY ([DATABASE_INSTANCE_ID]) REFERENCES [dbo].[SYS_DATABASE_INSTANCE] ([ID])
);

