CREATE TABLE [dbo].[SYS_COLUMN_SET] (
    [ID]                        BIGINT        IDENTITY (1, 1) NOT NULL,
    [DATABASE_TABLE_ID]         BIGINT        NULL,
    [NAME]                      VARCHAR (200) NULL,
    [IS_PRIMARY_KEY]            BIT           NOT NULL,
    [MESSAGE_GROUP_INSTANCE_ID] BIGINT        NULL,
    [COLUMN_DATA_TYPE]          VARCHAR (50)  NULL,
    CONSTRAINT [PK_SYS_COLUMN_SET] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SYS_COLUMN_SET_SYS_DATABASE_TABLE] FOREIGN KEY ([DATABASE_TABLE_ID]) REFERENCES [dbo].[SYS_DATABASE_TABLE] ([ID]),
    CONSTRAINT [FK_SYS_COLUMN_SET_SYS_MESSAGE_GROUP_INSTANCE] FOREIGN KEY ([MESSAGE_GROUP_INSTANCE_ID]) REFERENCES [dbo].[SYS_MESSAGE_GROUP_INSTANCE] ([ID])
);



