CREATE TABLE [dbo].[SYS_MESSAGE_GROUP_INSTANCE] (
    [ID]              BIGINT         IDENTITY (1, 1) NOT NULL,
    [MESSAGE_TYPE_ID] BIGINT         NULL,
    [SEGMENT_TYPE_ID] BIGINT         NULL,
    [CREATED_DTTM]    DATETIME       NULL,
    [UPDATED_DTTM]    DATETIME       NULL,
    [DESCRIPTION]     NVARCHAR (255) NULL,
    CONSTRAINT [PK_SYS_MESSAGE_GROUP_INSTANCE] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SYS_MESSAGE_GROUP_INSTANCE_SYS_MESSAGE_TYPE] FOREIGN KEY ([MESSAGE_TYPE_ID]) REFERENCES [dbo].[SYS_MESSAGE_TYPE] ([ID]),
    CONSTRAINT [FK_SYS_MESSAGE_GROUP_INSTANCE_SYS_SEGMENT_TYPE] FOREIGN KEY ([SEGMENT_TYPE_ID]) REFERENCES [dbo].[SYS_SEGMENT_TYPE] ([ID])
);

