CREATE TABLE [dbo].[SYS_INTERFACE_STATUS] (
    [ID]           INT            IDENTITY (1, 1) NOT NULL,
    [NAME]         NVARCHAR (100) NOT NULL,
    [STATUS_COLOR] NVARCHAR (100) NOT NULL,
    CONSTRAINT [PK_APP_INTERFACE_STATUS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

