CREATE TABLE [dbo].[SYS_DATABASE_TABLE_RELATION] (
    [ID]                       BIGINT IDENTITY (1, 1) NOT NULL,
    [SOURCE_DATABASE_TABLE_ID] BIGINT NOT NULL,
    [TARGET_DATABASE_TABLE_ID] BIGINT NOT NULL,
    [REQUIRES_IDENTITY]        BIT    NOT NULL,
    CONSTRAINT [FK_SYS_DATABASE_TABLE_RELATION_SYS_DATABASE_TABLE] FOREIGN KEY ([SOURCE_DATABASE_TABLE_ID]) REFERENCES [dbo].[SYS_DATABASE_TABLE] ([ID]),
    CONSTRAINT [FK_SYS_DATABASE_TABLE_RELATION_SYS_DATABASE_TABLE1] FOREIGN KEY ([TARGET_DATABASE_TABLE_ID]) REFERENCES [dbo].[SYS_DATABASE_TABLE] ([ID])
);

