CREATE TABLE [dbo].[SYS_WEBSERVICE_OBJECT] (
    [ID]                     BIGINT        IDENTITY (1, 1) NOT NULL,
    [WEBSERVICE_INSTANCE_ID] BIGINT        NULL,
    [NAME]                   VARCHAR (100) NULL,
    CONSTRAINT [PK_SYS_WEBSERVICE_OBJECT] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SYS_WEBSERVICE_OBJECT_SYS_WEBSERVICE_INSTANCE] FOREIGN KEY ([WEBSERVICE_INSTANCE_ID]) REFERENCES [dbo].[SYS_WEBSERVICE_INSTANCE] ([ID])
);

