CREATE TABLE [dbo].[SYS_APPLICATION] (
    [ID]          BIGINT        IDENTITY (1, 1) NOT NULL,
    [NAME]        VARCHAR (200) NULL,
    [DESCRIPTION] VARCHAR (200) NULL,
    CONSTRAINT [PK_SYS_APPLICATION] PRIMARY KEY CLUSTERED ([ID] ASC)
);

