ALTER DATABASE [$(DatabaseName)]
    ADD FILE (NAME = [SHIELDS_INTERFACE_BROKER], FILENAME = 'D:\MSSQL11.MSSQLSERVER\MSSQL\DATA\SHIELDS_INTERFACE_BROKER.mdf', SIZE = 985088 KB, FILEGROWTH = 1024 KB) TO FILEGROUP [PRIMARY];

