ALTER DATABASE [$(DatabaseName)]
    ADD LOG FILE (NAME = [SHIELDS_INTERFACE_BROKER_log], FILENAME = 'E:\MSSQL11.MSSQLSERVER\MSSQL\LOG\SHIELDS_INTERFACE_BROKER_log.ldf', SIZE = 230272 KB, MAXSIZE = 2097152 MB, FILEGROWTH = 10 %);

